import type { Metadata } from 'next';
import SiteNav from '@/components/ui/site-nav';

export const metadata: Metadata = {
  title: 'Blog',
  description: 'Tips, updates and stories from the Vibbr team.',
};

const POSTS = [
  {
    tag: 'AI',
    title: 'How AI is changing web design for small businesses',
    date: 'April 15, 2025',
    excerpt:
      'Discover how business owners are saving thousands on web design by using AI tools to build professional sites in minutes.',
  },
  {
    tag: 'SEO',
    title: 'SEO best practices built into every Vibbr site',
    date: 'April 10, 2025',
    excerpt:
      'Every site generated by Vibbr includes meta tags, JSON-LD schema, Open Graph, and a sitemap automatically.',
  },
  {
    tag: 'Product',
    title: 'From prompt to live website in under 60 seconds',
    date: 'April 5, 2025',
    excerpt:
      "We tested 50 different prompts and measured generation time. Here's what we learned about writing great prompts.",
  },
];

export default function BlogPage() {
  return (
    <div className="min-h-screen" style={{ background: '#0f0f12' }}>
      {/* Background orbs */}
      <div className="fixed inset-0 pointer-events-none" style={{ zIndex: 0 }}>
        <div
          style={{
            position: 'absolute',
            width: 600, height: 600,
            top: -100, left: -100,
            background: 'radial-gradient(circle, rgba(139,92,246,0.3) 0%, transparent 70%)',
            filter: 'blur(80px)',
          }}
        />
        <div
          style={{
            position: 'absolute',
            width: 400, height: 400,
            bottom: 0, right: 0,
            background: 'radial-gradient(circle, rgba(236,72,153,0.2) 0%, transparent 70%)',
            filter: 'blur(80px)',
          }}
        />
      </div>

      <SiteNav />

      <main className="relative z-10 pt-32 pb-20 px-6">
        {/* Header */}
        <div className="text-center mb-12">
          <h1 className="text-5xl font-extrabold text-white tracking-tight">Blog</h1>
          <p className="mt-3 text-zinc-400">Tips, updates and stories from the Vibbr team.</p>
        </div>

        {/* Posts grid */}
        <div className="max-w-4xl mx-auto grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {POSTS.map((post) => (
            <div
              key={post.title}
              className="bg-white/5 border border-white/10 rounded-2xl p-6 hover:border-white/20 transition-all cursor-pointer"
            >
              <span className="bg-orange-500/10 text-orange-400 text-xs rounded-full px-2 py-0.5">
                {post.tag}
              </span>
              <h2 className="text-white font-semibold text-lg mt-2">{post.title}</h2>
              <p className="text-zinc-400 text-sm mt-2">{post.excerpt}</p>
              <p className="text-zinc-600 text-xs mt-4">{post.date}</p>
            </div>
          ))}
        </div>
      </main>
    </div>
  );
}
