'use client';

import { useState } from 'react';

interface Post {
  id: string;
  tag: string;
  title: string;
  date: string;
  excerpt: string;
  content: string;
}

const POSTS: Post[] = [
  {
    id: 'ai-web-design',
    tag: 'AI',
    title: 'How AI is changing web design for small businesses',
    date: 'April 15, 2025',
    excerpt:
      'Discover how business owners are saving thousands on web design by using AI tools to build professional sites in minutes.',
    content: `
For years, getting a professional website meant one of two paths: hiring a web agency for €3,000–€10,000, or spending weeks learning a page builder and settling for a generic template. Neither option was great for a small business owner who just needed to get online.

That's changing fast.

**The old model is broken**

Traditional web design agencies charge for time: designer hours, developer hours, revision rounds, project management. A simple five-page site for a local restaurant could easily cost €4,000 and take six weeks to launch. By the time it went live, the restaurant had already lost months of potential customers searching Google and finding nothing.

Page builders like Wix and Squarespace brought costs down but introduced new friction. You still had to become a part-time designer, choose the right template, customise every section, write all the copy yourself, and figure out SEO on your own. Most business owners gave up partway through or launched something they were quietly embarrassed about.

**AI changes the equation entirely**

The new generation of AI website builders doesn't ask you to become a designer. You describe your business — what you do, where you are, who you serve — and the AI writes the copy, chooses the layout, generates the HTML, CSS and JavaScript, and produces a live site with SEO built in.

The result isn't a template with your logo swapped in. It's a site written specifically for your business, with real content that reflects what makes you different.

For a moving company owner in Porto, that means: a hero section explaining their service area, a list of what they move, a pricing section with transparent tiers, customer reviews, and a contact form that says "Get a free quote" — all generated from a two-sentence description.

**What this means for small businesses**

Three things are happening simultaneously:

1. **Cost drops from thousands to tens of euros.** A subscription to an AI web builder costs less than a single hour of agency time. For businesses that couldn't previously afford a professional site, this is transformative.

2. **Time drops from weeks to minutes.** There's no brief, no design rounds, no development sprints. The site is live before your coffee gets cold.

3. **Quality goes up.** Because AI-generated sites are built from scratch for each business, they read authentically. The copy doesn't sound templated. The structure reflects the business's actual priorities.

**The businesses benefiting most**

The biggest winners are service businesses — tradespeople, restaurants, consultants, therapists, fitness instructors — who have always needed a credible web presence but could never justify the cost. Now a plumber can have a site that ranks on Google for "emergency plumber [city]" without paying an SEO agency.

Agencies are also rethinking their workflow. Instead of spending three days on a basic client site, they can generate a solid foundation in minutes and spend their time on the work that actually requires human judgment — brand strategy, custom features, long-term SEO.

**The limits are real but narrowing**

AI-generated sites are excellent for most business needs: lead generation, local SEO, service pages, portfolios, menus, booking CTAs. They're not yet the right tool for complex e-commerce stores, membership sites, or applications that require custom backend logic.

But for the 90% of small businesses that just need a professional, fast-loading, SEO-ready site that accurately represents what they do — AI web design is no longer a compromise. It's the better option.
    `.trim(),
  },
  {
    id: 'seo-practices',
    tag: 'SEO',
    title: 'SEO best practices built into every Vibbr site',
    date: 'April 10, 2025',
    excerpt:
      'Every site generated by Vibbr includes meta tags, JSON-LD schema, Open Graph, and a sitemap automatically.',
    content: `
When we designed Vibbr's generation engine, we made a deliberate decision: SEO shouldn't be an add-on. It should be default infrastructure — present in every site, whether you ask for it or not.

Here's exactly what that means and why it matters.

**Meta tags: the basics, done right**

Every Vibbr site includes a \`<title>\` tag and \`<meta name="description">\` that are written specifically for the business. Not generic placeholders. Not truncated keyword dumps. Real, readable titles and descriptions that describe the business accurately and include natural keyword placement.

The title follows the format most Google engineers recommend: *[Business Name] — [Primary Service] in [City]*. The description is 150–160 characters: long enough to be informative, short enough not to be truncated in search results.

**JSON-LD schema markup**

This is where most DIY sites fall short. Schema markup is structured data that tells search engines exactly what type of entity your site represents — a restaurant, a local business, a portfolio, a product. Without it, Google has to guess.

Every Vibbr site includes appropriate JSON-LD schema. A restaurant gets \`Restaurant\` schema with name, address, opening hours, cuisine type and price range. A local service business gets \`LocalBusiness\` schema with service area and contact details. A portfolio gets \`Person\` schema with job title and professional links.

This structured data makes your site eligible for rich results in Google — the enhanced listings that show star ratings, opening hours, or FAQs directly in search results. Rich results consistently see higher click-through rates than standard blue links.

**Open Graph tags for social sharing**

When someone shares your site on LinkedIn, Twitter, WhatsApp or Facebook, the platform reads Open Graph tags to generate the preview card — the image, title and description that appear before the link.

Without Open Graph tags, social platforms either show a broken preview or scrape random content from the page. With them, you control exactly what people see when your site gets shared.

Vibbr generates \`og:title\`, \`og:description\`, \`og:url\` and \`og:type\` on every site. For businesses that rely on word-of-mouth and social sharing, this is meaningful: a well-formatted preview card gets clicks; a blank one gets ignored.

**Sitemap.xml**

A sitemap tells Google which pages exist on your site and when they were last updated. It's how search engines discover your content efficiently — especially for new sites that don't yet have many inbound links.

Every Vibbr site includes a \`sitemap.xml\` at the root. The moment your site goes live, it's discoverable.

**Canonical URLs**

Duplicate content — the same page accessible at multiple URLs — confuses search engines and splits your ranking signals. Vibbr sets canonical URLs on every page to declare the authoritative version, preventing accidental duplication from URL parameters or trailing slashes.

**What this means in practice**

For a small business owner, this translates to one thing: you don't need to hire an SEO consultant to fix your site's technical foundation. It's already done. What remains is the harder, longer-term work of building backlinks and producing content — but you start from a solid technical base rather than a broken one.

For agencies using Vibbr to build client sites, it means every deliverable is already SEO-compliant. No extra charge for "SEO setup". No checklist to work through before handoff. It's just there.

We benchmark every generated site against Google's Lighthouse SEO audit. The target is 90+. It's consistently met.
    `.trim(),
  },
  {
    id: 'prompt-to-website',
    tag: 'Product',
    title: 'From prompt to live website in under 60 seconds',
    date: 'April 5, 2025',
    excerpt:
      "We tested 50 different prompts and measured generation time. Here's what we learned about writing great prompts.",
    content: `
We ran 50 generations over two weeks and timed every one. The average time from pressing Enter to a fully published, live website was 38 seconds. The fastest was 22 seconds. The slowest was 61 seconds.

But speed wasn't the interesting finding. The interesting finding was how much the quality of the prompt affected the quality of the output.

**What we tested**

We picked five categories of business — restaurants, service businesses, portfolios, agencies and SaaS products — and wrote ten prompts per category ranging from extremely vague to highly specific.

Vague: *"restaurant website"*
Specific: *"Website for a family-run Neapolitan pizza restaurant in Lisbon called Forno do Bairro. Casual, warm atmosphere. Known for wood-fired pizza and natural wine. Open Tuesday–Sunday, 12–3pm and 6–11pm. Reservations via phone."*

The results weren't close. The vague prompt produced a serviceable generic site. The specific prompt produced a site that read like it was written by someone who'd eaten there — with real copy, the right tone, and details that made it credible.

**The three things that matter most**

After reviewing all 50 outputs, we identified three things that consistently improved quality:

**1. Name and location**

The single biggest quality jump came from including the business name and city. Without a name, the generated copy uses placeholders. With a name and city, the site reads like a real business — and the SEO tags include location keywords automatically.

*Before:* "Our team of professionals will help you move stress-free."
*After (with name + city):* "Mudanças Fáceis has been helping families and businesses move across Porto since 2018."

**2. Tone and audience**

Telling Vibbr who the customers are — and what tone fits the brand — makes a significant difference. "Professional and trustworthy" produces different copy than "casual and friendly". Neither is wrong; they're right for different businesses.

A therapy practice that wants to feel safe and calm needs different language than a streetwear brand that wants to feel edgy and direct. The more specific you are, the closer the first generation gets.

**3. Key differentiators and specific details**

What makes this business different? What do customers say? What details would a good copywriter emphasise?

Include: specialties, years in business, notable clients or projects, awards, specific services with prices if relevant, anything that would make a prospective customer trust you faster.

*Weak:* "Include a services section."
*Strong:* "Services: full household moves, office relocations, piano moving, and packing service. We're the only moving company in the area with a dedicated piano team."

**What we learned about iteration**

Even with a weak first prompt, the editing workflow is fast. You can regenerate sections with additional context, or edit with natural language instructions: "Make the hero section more energetic" or "Add a FAQ about insurance coverage."

The best approach is: write a good prompt and generate once, then refine with two or three edits. This almost always produces a better result than trying to get everything perfect in the first prompt — because seeing the first version helps you understand what's missing.

**The prompts that didn't work**

A few patterns consistently produced mediocre results:

- Prompts focused on aesthetics rather than content: *"Make it look modern and clean with a dark background"* — design preferences are better handled in edits after seeing the first version
- Prompts that conflated multiple businesses: *"A restaurant and a catering service and an events venue"* — pick the primary business; secondary offerings can be added in edits
- Prompts that were just a website URL or company name with no context — the AI has no way to know what the business actually does

**The formula**

If you want to get the best result on your first generation, use this structure:

*[Business name] in [City/Location]. [What they do in one sentence]. [Who their customers are]. [Key differentiator]. [Specific details: hours, prices, services, team]. [Desired tone].*

You'll rarely need more than 3–4 sentences. And you'll be live in under 60 seconds.
    `.trim(),
  },
];

export default function BlogContent() {
  const [openPost, setOpenPost] = useState<string | null>(null);

  return (
    <div className="max-w-4xl mx-auto grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
      {POSTS.map((post) => {
        const isOpen = openPost === post.id;
        return (
          <div
            key={post.id}
            className={[
              'bg-white/5 border rounded-2xl transition-all duration-300',
              isOpen ? 'border-white/20 sm:col-span-2 lg:col-span-3' : 'border-white/10 hover:border-white/20',
            ].join(' ')}
          >
            {/* Card header — always visible */}
            <div className="p-6">
              <div className="flex items-start justify-between gap-3">
                <div className="flex-1 min-w-0">
                  <span className="bg-orange-500/10 text-orange-400 text-xs rounded-full px-2 py-0.5">
                    {post.tag}
                  </span>
                  <h2 className="text-white font-semibold text-lg mt-2 leading-snug">{post.title}</h2>
                  <p className="text-zinc-400 text-sm mt-2">{post.excerpt}</p>
                  <p className="text-zinc-600 text-xs mt-4">{post.date}</p>
                </div>
                {isOpen && (
                  <button
                    type="button"
                    onClick={() => setOpenPost(null)}
                    className="shrink-0 w-7 h-7 rounded-full bg-white/10 hover:bg-white/20 flex items-center justify-center text-zinc-400 hover:text-white transition-colors text-sm font-medium"
                    aria-label="Close article"
                  >
                    ×
                  </button>
                )}
              </div>

              {!isOpen && (
                <button
                  type="button"
                  onClick={() => setOpenPost(post.id)}
                  className="mt-4 text-sm font-medium text-orange-400 hover:text-orange-300 transition-colors"
                >
                  Read more →
                </button>
              )}
            </div>

            {/* Expandable article body */}
            <div
              style={{
                maxHeight: isOpen ? '9999px' : '0',
                overflow: 'hidden',
                transition: 'max-height 0.4s ease',
              }}
            >
              <div className="px-6 pb-8 border-t border-white/8 pt-6">
                <div className="prose prose-sm max-w-none text-zinc-300 leading-relaxed">
                  {post.content.split('\n\n').map((para, i) => {
                    if (para.startsWith('**') && para.endsWith('**')) {
                      return (
                        <h3 key={i} className="text-white font-semibold text-base mt-6 mb-2">
                          {para.slice(2, -2)}
                        </h3>
                      );
                    }
                    // Inline bold: replace **text** with <strong>
                    const parts = para.split(/(\*\*[^*]+\*\*)/g);
                    return (
                      <p key={i} className="mb-4 text-zinc-400 text-sm leading-relaxed">
                        {parts.map((part, j) =>
                          part.startsWith('**') && part.endsWith('**')
                            ? <strong key={j} className="text-zinc-200 font-semibold">{part.slice(2, -2)}</strong>
                            : part
                        )}
                      </p>
                    );
                  })}
                </div>
              </div>
            </div>
          </div>
        );
      })}
    </div>
  );
}
